
server:
  port: 8080
  servlet:
    session:
      #tracking-modes:
      #- cookie
      timeout: 30m
      cookie:
        name: K_IDF
        http-only: true
  tomcat:
    additional-tld-skip-patterns: "jaxb*.jar"
    max-swallow-size: 1

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      
mybatis:
  type-aliases-package: com.sys.bo.*.*.domain
  mapper-locations: classpath:mapper/**/*-sql.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true

upload:
  filePath: D:\upload    
---
spring:
  profiles: local
  datasource: 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  
      
logging:
  level:
    org.springframework: error
    #com.skm.sso: info
    #worg.hibernate.type: info
    jdbc.audit: off
    jdbc.connection: off
    jdbc.resultset: off
    jdbc.sqlonly: error